image: ubuntu

before_script:  
  - curl -fsSL https://tailscale.com/install.sh | sh
  - apt-get update -qq && apt-get install
  - apt install -y curl tailscale rsync unixodbc-common unixodbc-dev libodbc2 libodbccr2 libodbcinst2 nodejs           
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - cat "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - tailscale up --authkey=tskey-auth-k7wF4gtXcL11CNTRL-NxhPEnBPRBX8h7zNdf9pEXdf97X9EeTK --hostname="gitlab-$(cat /etc/hostname)"
  - tailscale ip
  - ping 100.84.134.109

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy


build dev:
  stage: build
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: 30 days
    paths: 
      - '**'

  only:
    - dev
  script:
    - echo -n $ENV_FILE | base64 -d > .env
    - cat .env
    - sed -i "s/{COMMIT}/$CI_COMMIT_REF_SLUG $CI_COMMIT_SHORT_SHA/g" pages/login.vue
    - yarn
    - yarn build

deploy development:
  stage: deploy
  only:
    - dev
  script:
#    - echo 'NUXT_UI_PRO_LICENSE=DE96572D-DF69-4CE2-8359-220121662EBA' > .env
    - rsync -azh --rsh="ssh -o StrictHostKeyChecking=no -l ubuntu" ./** ubuntu@3.132.84.177:/var/www/gms/grimm-management-system-web
    - ssh -o StrictHostKeyChecking=no ubuntu@3.132.84.177 "pm2 restart all"


