image: node

before_script:
  - apt-get update -qq && apt install -y -qq curl rsync unixodbc-common unixodbc-dev libodbc2 libodbccr2 libodbcinst2 iputils-ping openssh-client
  - eval $(ssh-agent -s)
  - cat "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

cache:
  paths:
    - node_modules/
    - .yarn-cache
stages:
  - test
  - build
  - deploy

build test:
  stage: test
  artifacts:
    when: on_success
    expire_in: 30 days
    paths:
      - .nuxt
      - .output
      - node_modules
  except:
    - main
    - dev
  script:
    - echo -n $ENV_FILE | base64 -d > .env
    - sed -i "s/{COMMIT}/$CI_COMMIT_REF_SLUG $CI_COMMIT_SHORT_SHA/g" ./pages/login.vue
    - sed -i "s/{COMMIT}/$CI_COMMIT_REF_SLUG $CI_COMMIT_SHORT_SHA/g" ./components/common/UserDropdown.vue
    - yarn install --cache-folder .yarn-cache
    - yarn build --fail-on-error

build dev:
  stage: build
  artifacts:
    when: on_success
    expire_in: 30 days
    paths:
      - .nuxt
      - .output
      - node_modules
  script:
    - echo -n $ENV_FILE | base64 -d > .env
    - sed -i "s/{COMMIT}/$CI_COMMIT_REF_SLUG $CI_COMMIT_SHORT_SHA/g" ./pages/login.vue
    - sed -i "s/{COMMIT}/$CI_COMMIT_REF_SLUG $CI_COMMIT_SHORT_SHA/g" ./components/common/UserDropdown.vue
    - yarn install --cache-folder .yarn-cache
    - yarn build --fail-on-error

deploy development:
  stage: deploy
  only:
    - dev
  script:
    - rsync -azhz --delete --rsh="ssh -o StrictHostKeyChecking=no -l gitlab" ./ gitlab@192.168.13.158:/var/storage/apps/gms/grimm-management-system-web/
    - ssh -o StrictHostKeyChecking=no gitlab@192.168.13.158 "pm2 restart gms"
