image: node:lts

before_script:  
  - apt-get update -qq && apt-get install
  - apt install -y rsync unixodbc-common unixodbc-dev libodbc2 libodbccr2 libodbcinst2           
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - cat "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

#cache:
#  paths:
#    - node_modules/
#    - .yarn

stages:
  - build
  - deploy


build dev:
  stage: build
  only:
    - dev
  script:
    - echo 'NUXT_UI_PRO_LICENSE=DE96572D-DF69-4CE2-8359-220121662EBA' > .env
    - yarn
    - yarn generate

deploy development:
  stage: deploy
  only:
    - dev
  script:
#    - cd bba-client
#    - sed -i "s/{COMMIT}/$CI_COMMIT_REF_SLUG $CI_COMMIT_SHORT_SHA/g" components/paradym/Navigation.vue
#    - yarn
#    - yarn generate
    - echo 'NUXT_UI_PRO_LICENSE=DE96572D-DF69-4CE2-8359-220121662EBA' > .env
    - rsync -azh --rsh="ssh -o StrictHostKeyChecking=no -l ubuntu" ./../** ubuntu@3.132.84.177:/var/www/gms/grimm-management-system-web
    - ssh -o StrictHostKeyChecking=no ubuntu@3.132.84.177 "pm2 restart all"


