image: node

before_script:  
  - apt-get update -qq && apt-get install
  - apt install -y curl rsync unixodbc-common unixodbc-dev libodbc2 libodbccr2 libodbcinst2 iputils-ping    
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - cat "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy


build dev:
  stage: build
  artifacts:
    when: on_success
    expire_in: 30 days
    paths: 
      - '**'
  only:
    - dev
  script:
    - echo -n $ENV_FILE | base64 -d > .env
#    - echo 'NUXT_UI_PRO_LICENSE=DE96572D-DF69-4CE2-8359-220121662EBA' >> .env
    - cat .env
    - sed -i "s/{COMMIT}/$CI_COMMIT_REF_SLUG $CI_COMMIT_SHORT_SHA/g" pages/login.vue
    - yarn
    - yarn build --fail-on-error
    
deploy development:
  stage: deploy
  only:
    - dev
  script:
#    - rsync -azh --rsh="ssh -o StrictHostKeyChecking=no -l ubuntu" ./** ubuntu@3.132.84.177:/var/www/gms/grimm-management-system-web
    - rsync -azh --rsh="ssh -o StrictHostKeyChecking=no -l gitlab" ./** gitlab@100.69.4.76:/var/storage/apps/gms/grimm-management-system-web/
    - ssh -o StrictHostKeyChecking=no gitlab@100.69.4.76 "pm2 restart gms"


