npmScopes: {
  bryntum: {
    npmRegistryServer: https://npm.bryntum.com,
    npmAlwaysAuth: true,
    npmAuthIdent: sshere..imagi-tech.com
    npmAuthToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWFsX2dyb3VwcyI6WyJ0cmlhbCJdLCJuYW1lIjoic3RlcGhhbi4uaW1hZ2ktdGVjaC5jb20iLCJncm91cHMiOlsidHJpYWwiLCIkYWxsIiwiJGF1dGhlbnRpY2F0ZWQiLCJAYWxsIiwiQGF1dGhlbnRpY2F0ZWQiLCJhbGwiXSwiaWF0IjoxNzIwODczMDUwLCJuYmYiOjE3MjA4NzMwNTAsImV4cCI6MjU4NDc4NjY1MH0.w88AcYU1zHB91ryDr6saI-cIyK2AKy9_2KEaYf7cEPg
  }
}