npmScopes: {
  bryntum: {
    npmRegistryServer: https://npm.bryntum.com,
    npmAlwaysAuth: true,
    npmAuthIdent: stephan..imagi-tech.com,
    npmAuthToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWFsX2dyb3VwcyI6WyJ0cmlhbCJdLCJuYW1lIjoic3RlcGhhbi4uaW1hZ2ktdGVjaC5jb20iLCJncm91cHMiOlsidHJpYWwiLCIkYWxsIiwiJGF1dGhlbnRpY2F0ZWQiLCJAYWxsIiwiQGF1dGhlbnRpY2F0ZWQiLCJhbGwiXSwiaWF0IjoxNzIwODQyMTQ4LCJuYmYiOjE3MjA4NDIxNDgsImV4cCI6MjU4NDc1NTc0OH0.Qr6Nsn_gzKHNmo-dREakRw8UQ0T0KwtlxiSbwUf_RO4
  }
}